###
GET http://localhost:8080/products/27

// http GET :8080/products/9


###
GET http://localhost:8080/products?size=12&page=0&sort=name,desc

// httpe nao esta funcionado....
// http GET :8080/products?size=2&page=0&sort=name

###
GET http://localhost:8080/products/no-pageable

// http GET :8080/products/no-pageable


###
POST http://localhost:8080/products
Content-Type:  application/json

{
    "name": "Meu novo produto",
    "description": "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Qui ad, adipisci illum ipsam velit et odit eaque reprehenderit ex maxime delectus dolore labore, quisquam quae tempora natus esse aliquam veniam doloremque quam minima culpa alias maiores commodi. Perferendis enim",
    "imgUrl": "https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg",
    "price": 200.0
}

// COM O HTTPIE -> http POST :4000/auth/login